import {ThemeType} from './types';

export const colors = {
  theme: {primary: '#459A95', secondary: '#002408'},
  white: '#FFFFFF',
  black: '#000000',
  borderColor: '#D9D9D9',
  grey: 'grey',
  grey1: '#C1C1C1',
  greyText: '#6E6E6E',
  orange: '#FE8E26',
  disabled: 'rgba(0,0,0,0.2)',
  red: '#FF0000',
  green: '#00A300',
};

export const FONT_SIZES = [
  {name: 'small', value: 12},
  {name: 'regular', value: 14},
  {name: 'medium', value: 16},
  {name: 'large', value: 18},
  {name: 'xl', value: 20},
  {name: 'xxl', value: 22},
];

export const THEMES: ThemeType[] = [
  {
    name: 'Light',
    nature: 'light',
    primaryColor: '#fff',
    primaryTextColor: '#000',
    secondaryColor: '#000',
    secondaryTextColor: '#fff',
    statusBarColor: '#fff',
    statusBarStyle: 'light-content',
    textColor: '#fff',
    surfaceBGColor: '#ddd',
    borderColor: '#000',
    inputBGColor: '#fff',
    inputBorderColor: '#000',
    inputTextColor: '#000',
    inputPlaceholderColor: '#C1C1C1',
    buttonBGColor: '#000',
    buttonBGDisableColor: '#000',
    buttonTextColor: '#fff',
    linkColor: '#000',
  },
  {
    name: 'Dark',
    nature: 'dark',
    primaryColor: '#000',
    primaryTextColor: '#fff',
    secondaryColor: '#fff',
    secondaryTextColor: '#000',
    statusBarColor: '#000',
    statusBarStyle: 'light-content',
    textColor: '#fff',
    surfaceBGColor: '#252424',
    borderColor: '#fff',
    inputBGColor: '#fff',
    inputBorderColor: '#000',
    inputTextColor: '#000',
    inputPlaceholderColor: '#C1C1C1',
    buttonBGColor: '#fff',
    buttonBGDisableColor: '#fff',
    buttonTextColor: '#000',
    linkColor: '#fff',
  },
  {
    name: 'Green',
    nature: 'light',
    primaryColor: '#008000',
    primaryTextColor: '#fff',
    secondaryColor: '#fff',
    secondaryTextColor: '#000',
    statusBarColor: '#008000',
    statusBarStyle: 'light-content',
    textColor: '#fff',
    surfaceBGColor: '#00BFA5',
    borderColor: '#D9D9D9',
    inputBGColor: '#fff',
    inputBorderColor: '#008000',
    inputTextColor: '#fff',
    inputPlaceholderColor: '#C1C1C1',
    buttonBGColor: '#008000',
    buttonBGDisableColor: '#008000',
    buttonTextColor: '#fff',
    linkColor: '#008000',
  },
  {
    name: 'Teal',
    nature: 'light',
    primaryColor: '#3fbbc0',
    primaryTextColor: '#000',
    secondaryColor: '#fff',
    secondaryTextColor: '#000',
    statusBarColor: '#3fbbc0',
    statusBarStyle: 'light-content',
    textColor: '#010203',
    surfaceBGColor: '#f7f8f9',
    borderColor: '#D9D9D9',
    inputBGColor: '#fff',
    inputBorderColor: '#3fbbc0',
    inputTextColor: '#010203',
    inputPlaceholderColor: '#C1C1C1',
    buttonBGColor: '#3fbbc0',
    buttonBGDisableColor: '#3fbbc0',
    buttonTextColor: '#fff',
    linkColor: '#3fbbc0',
  },
  {
    name: 'Red',
    nature: 'light',
    primaryColor: '#f50002',
    primaryTextColor: '#000',
    secondaryColor: '#fff',
    secondaryTextColor: '#000',
    statusBarColor: '#f50002',
    statusBarStyle: 'light-content',
    textColor: '#010203',
    surfaceBGColor: '#fff',
    borderColor: '#D9D9D9',
    inputBGColor: '#fff',
    inputBorderColor: '#f50002',
    inputTextColor: '#010203',
    inputPlaceholderColor: '#C1C1C1',
    buttonBGColor: '#f50002',
    buttonBGDisableColor: '#f50002',
    buttonTextColor: '#fff',
    linkColor: '#f50002',
  },
  {
    name: 'Blue',
    nature: 'light',
    primaryColor: '#003194',
    primaryTextColor: '#fff',
    secondaryColor: '#fff',
    secondaryTextColor: '#000',
    statusBarColor: '#003194',
    statusBarStyle: 'dark-content',
    textColor: '#010203',
    surfaceBGColor: '#fff',
    borderColor: '#D9D9D9',
    inputBGColor: '#fff',
    inputBorderColor: '#003194',
    inputTextColor: '#010203',
    inputPlaceholderColor: '#C1C1C1',
    buttonBGColor: '#003194',
    buttonBGDisableColor: '#003194',
    buttonTextColor: '#fff',
    linkColor: '#003194',
  },
  {
    name: 'Purple',
    nature: 'light',
    primaryColor: '#7c007c',
    primaryTextColor: '#000',
    secondaryColor: '#fff',
    secondaryTextColor: '#000',
    statusBarColor: '#7c007c',
    statusBarStyle: 'light-content',
    textColor: '#010203',
    surfaceBGColor: '#fff',
    borderColor: '#D9D9D9',
    inputBGColor: '#fff',
    inputBorderColor: '#7c007c',
    inputTextColor: '#010203',
    inputPlaceholderColor: '#C1C1C1',
    buttonBGColor: '#7c007c',
    buttonBGDisableColor: '#7c007c',
    buttonTextColor: '#fff',
    linkColor: '#7c007c',
  },
  {
    name: 'Pink',
    nature: 'light',
    primaryColor: '#ff3399',
    primaryTextColor: '#000',
    secondaryColor: '#fff',
    secondaryTextColor: '#000',
    statusBarColor: '#ff3399',
    statusBarStyle: 'light-content',
    textColor: '#010203',
    surfaceBGColor: '#fff',
    borderColor: '#D9D9D9',
    inputBGColor: '#fff',
    inputBorderColor: '#ff3399',
    inputTextColor: '#010203',
    inputPlaceholderColor: '#C1C1C1',
    buttonBGColor: '#ff3399',
    buttonBGDisableColor: '#ff3399',
    buttonTextColor: '#fff',
    linkColor: '#ff3399',
  },
  {
    name: 'Gray',
    nature: 'light',
    primaryColor: '#767171',
    primaryTextColor: '#000',
    secondaryColor: '#fff',
    secondaryTextColor: '#000',
    statusBarColor: '#767171',
    statusBarStyle: 'light-content',
    textColor: '#010203',
    surfaceBGColor: '#fff',
    borderColor: '#D9D9D9',
    inputBGColor: '#fff',
    inputBorderColor: '#767171',
    inputTextColor: '#010203',
    inputPlaceholderColor: '#C1C1C1',
    buttonBGColor: '#767171',
    buttonBGDisableColor: '#767171',
    buttonTextColor: '#fff',
    linkColor: '#767171',
  },
  {
    name: 'Orange',
    nature: 'light',
    primaryColor: '#ff914d',
    primaryTextColor: '#000',
    secondaryColor: '#fff',
    secondaryTextColor: '#000',
    statusBarColor: '#ff914d',
    statusBarStyle: 'light-content',
    textColor: '#010203',
    surfaceBGColor: '#fff',
    borderColor: '#D9D9D9',
    inputBGColor: '#fff',
    inputBorderColor: '#ff914d',
    inputTextColor: '#010203',
    inputPlaceholderColor: '#C1C1C1',
    buttonBGColor: '#ff914d',
    buttonBGDisableColor: '#ff914d',
    buttonTextColor: '#fff',
    linkColor: '#ff914d',
  },
];

export const hexToRGBA = (hex: string | undefined, opacity: number = 1) => {
  let c: any;
  if (hex && /^#([A-Fa-f0-9]{3}){1,2}$/.test(hex)) {
    c = hex.substring(1).split('');
    if (c.length == 3) {
      c = [c[0], c[0], c[1], c[1], c[2], c[2]];
    }
    c = '0x' + c.join('');
    return (
      'rgba(' +
      [(c >> 16) & 255, (c >> 8) & 255, c & 255].join(',') +
      ',' +
      opacity +
      ')'
    );
  }
  // throw new Error('Bad Hex');
};
